export default {
  extends: ['stylelint-config-standard'],
  rules: {
    'at-rule-no-unknown': [true, {
      ignoreAtRules: [
        'apply',
        'config',
        'custom-variant',
        'plugin',
        'reference',
        'source',
        'theme',
        'utility',
        'variant',
      ],
    }],
    'declaration-block-no-duplicate-properties': true,
    'at-rule-empty-line-before': null,
    'alpha-value-notation': null,
    'color-function-alias-notation': null,
    'color-function-notation': null,
    'custom-property-empty-line-before': null,
    'declaration-block-no-shorthand-property-overrides': null,
    'declaration-block-no-redundant-longhand-properties': null,
    'declaration-empty-line-before': null,
    'declaration-block-single-line-max-declarations': null,
    'import-notation': null,
    'media-feature-range-notation': null,
    'no-descending-specificity': null,
    'no-duplicate-selectors': true,
    'property-no-unknown': true,
    'rule-empty-line-before': null,
    'selector-class-pattern': null,
    'shorthand-property-no-redundant-values': null,
    'value-keyword-case': null,
    'property-no-deprecated': null,
  },
};
